name: Deploy to GitHub Pages Repo
on:
  push:
    branches: [develop]  # ou o branch principal

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build static site
      run: |
        npm install
        npm run build
    

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Autenticar com Git
      run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit e Push
      run: |
        git checkout -b develop
        git add .
        git commit -m "Commit automático pela action" || echo "Nada para commitar"
        git push origin develop


    